### ISSUE TITLE
Resizing rive file crashes unreal

### ISSUE THREAD

**Issue by xanderseren** [rive-app/rive-unreal#79]
I'm on version 0.1.5. When importing a new rive file and attempting to adjust the size parameter in the details panel UE hangs and then the following error pops up. Selecting "Retry" just brings the error back up. Selecting "Abort" crashes the engine. This did not occur in the previous version 0.1.4

![Screenshot 2024-04-09 160848](https://github.com/rive-app/rive-unreal/assets/8236623/4ba406d1-0d45-4f23-9e9f-ff4ffe903256)

**Comment by Voulz** [comment]
Thanks @xanderseren, I was able to reproduce the issue with different steps.
Changing the size of the Rive File did not create the issue for me, but changing the size then undoing the change created the same error as the one you are showing.
We have updated the rive libraries in 0.1.5, which is probably why the error was not there before.
I'll start working on this in the coming days.

**Comment by Voulz** [comment]
@xanderseren, I have pushed a fix for this in the development branch for now, but more specifically avoiding this issue when the size is reverted on undo.
Could you test and let me know if that also fixes your issue?
Otherwise, could you confirm the platform and either, give me a step by step to reproduce, or provide a screen recording.
Thanks,
